set_property PACKAGE_PIN K17 [get_ports clk]
set_property PACKAGE_PIN E17 [get_ports rst_n]
set_property PACKAGE_PIN M15 [get_ports led[0]]
set_property PACKAGE_PIN G14 [get_ports led[1]]
set_property PACKAGE_PIN M17 [get_ports led[2]]
set_property PACKAGE_PIN G15 [get_ports led[3]]
set_property PACKAGE_PIN M19 [get_ports key[0]]
set_property PACKAGE_PIN M20 [get_ports key[1]]
set_property PACKAGE_PIN F16 [get_ports key[2]]
set_property PACKAGE_PIN L16 [get_ports key[3]]
set_property PACKAGE_PIN K18 [get_ports uart_txd]
set_property PACKAGE_PIN H15 [get_ports uart_rxd]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports led[*]]
set_property IOSTANDARD LVCMOS33 [get_ports key[*]]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]

create_clock -period 20.000 -name clk -waveform {0.000 10.000} [get_ports clk]
