+incdir+$PRJ_PATH/rtl/rv32im
+incdir+$PRJ_PATH/rtl/wb_conmax
+incdir+$PRJ_PATH/rtl/wb_gpio
+incdir+$PRJ_PATH/rtl/uart16550
+incdir+$PRJ_PATH/rtl/rv32im
$PRJ_PATH/rtl/sopc/riscv_sopc.v
$PRJ_PATH/rtl/sopc/rst_sync.v
$PRJ_PATH/rtl/wb_ram/wb_ram.v
$PRJ_PATH/rtl/wb_conmax/wb_conmax_top.v
$PRJ_PATH/rtl/wb_conmax/wb_conmax_slave_if.v
$PRJ_PATH/rtl/wb_conmax/wb_conmax_rf.v
$PRJ_PATH/rtl/wb_conmax/wb_conmax_pri_enc.v
$PRJ_PATH/rtl/wb_conmax/wb_conmax_pri_dec.v
$PRJ_PATH/rtl/wb_conmax/wb_conmax_msel.v
$PRJ_PATH/rtl/wb_conmax/wb_conmax_arb.v
$PRJ_PATH/rtl/wb_conmax/wb_conmax_master_if.v
$PRJ_PATH/rtl/rv32im/riscv_alu.v
$PRJ_PATH/rtl/rv32im/mem_fifo_wb.v
$PRJ_PATH/rtl/rv32im/riscv_idu.v
$PRJ_PATH/rtl/rv32im/riscv_ifu.v
$PRJ_PATH/rtl/rv32im/riscv_wb_top.v
$PRJ_PATH/rtl/rv32im/riscv_muldiv.v
$PRJ_PATH/rtl/rv32im/riscv_lsu.v
$PRJ_PATH/rtl/rv32im/riscv_exu.v
$PRJ_PATH/rtl/rv32im/riscv_csr.v
$PRJ_PATH/rtl/rv32im/riscv_core.v
$PRJ_PATH/rtl/rv32im/riscv_regfile.v
$PRJ_PATH/rtl/wb_gpio/gpio_top.v
$PRJ_PATH/rtl/uart16550/uart_receiver.v
$PRJ_PATH/rtl/uart16550/uart_rfifo.v
$PRJ_PATH/rtl/uart16550/uart_tfifo.v
$PRJ_PATH/rtl/uart16550/uart_debug_if.v
$PRJ_PATH/rtl/uart16550/uart_regs.v
$PRJ_PATH/rtl/uart16550/raminfr.v
$PRJ_PATH/rtl/uart16550/uart_wb.v
$PRJ_PATH/rtl/uart16550/uart_sync_flops.v
$PRJ_PATH/rtl/uart16550/uart_top.v
$PRJ_PATH/rtl/uart16550/uart_transmitter.v
