+define+AMBA_AXI4
+define+AMBA_AXI_CACHE
+define+AMBA_AXI_PROT
+incdir+../rtl/riscv/core
../rtl/sopc/riscv_sopc.v
../rtl/sopc/rst_sync.v
../rtl/sopc/axi_bus_2m4s.v
../rtl/sopc/axi4_ram_bridge.v
../rtl/sopc/ram.v
../rtl/riscv/core/riscv_alu.v
../rtl/riscv/core/riscv_decoder.v
../rtl/riscv/core/riscv_fetch.v
../rtl/riscv/core/riscv_xilinx_2r1w.v
../rtl/riscv/core/riscv_csr_regfile.v
../rtl/riscv/core/riscv_pipe_ctrl.v
../rtl/riscv/core/riscv_divider.v
../rtl/riscv/core/riscv_decode.v
../rtl/riscv/core/riscv_mmu.v
../rtl/riscv/core/riscv_issue.v
../rtl/riscv/core/riscv_lsu.v
../rtl/riscv/core/riscv_exec.v
../rtl/riscv/core/riscv_csr.v
../rtl/riscv/core/riscv_core.v
../rtl/riscv/core/riscv_multiplier.v
../rtl/riscv/core/riscv_regfile.v
../rtl/riscv/top_cache_axi/src_v/dcache_core_tag_ram.v
../rtl/riscv/top_cache_axi/src_v/dcache_if_pmem.v
../rtl/riscv/top_cache_axi/src_v/dcache_axi.v
../rtl/riscv/top_cache_axi/src_v/dcache_axi_axi.v
../rtl/riscv/top_cache_axi/src_v/icache_data_ram.v
../rtl/riscv/top_cache_axi/src_v/dcache.v
../rtl/riscv/top_cache_axi/src_v/dcache_mux.v
../rtl/riscv/top_cache_axi/src_v/dcache_core_data_ram.v
../rtl/riscv/top_cache_axi/src_v/icache_tag_ram.v
../rtl/riscv/top_cache_axi/src_v/dcache_pmem_mux.v
../rtl/riscv/top_cache_axi/src_v/icache.v
../rtl/riscv/top_cache_axi/src_v/dcache_core.v
../rtl/riscv/top_cache_axi/src_v/riscv_top.v
